// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// InquiryKnowledge is the predicate function for inquiryknowledge builders.
type InquiryKnowledge func(*sql.Selector)
