// Code generated by ent, DO NOT EDIT.

package dao

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	pgvector "github.com/pgvector/pgvector-go"
	"github.com/wonjinsin/simple-chatbot/internal/repository/postgres/dao/inquiryknowledge"
	"github.com/wonjinsin/simple-chatbot/internal/repository/postgres/dao/predicate"
	"github.com/wonjinsin/simple-chatbot/internal/repository/postgres/dao/user"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeInquiryKnowledge = "InquiryKnowledge"
	TypeUser             = "User"
)

// InquiryKnowledgeMutation represents an operation that mutates the InquiryKnowledge nodes in the graph.
type InquiryKnowledgeMutation struct {
	config
	op                    Op
	typ                   string
	id                    *int
	instruction           *string
	instruction_embedding *pgvector.Vector
	response              *string
	category              *string
	intent                *string
	flags                 *string
	created_at            *time.Time
	updated_at            *time.Time
	clearedFields         map[string]struct{}
	done                  bool
	oldValue              func(context.Context) (*InquiryKnowledge, error)
	predicates            []predicate.InquiryKnowledge
}

var _ ent.Mutation = (*InquiryKnowledgeMutation)(nil)

// inquiryknowledgeOption allows management of the mutation configuration using functional options.
type inquiryknowledgeOption func(*InquiryKnowledgeMutation)

// newInquiryKnowledgeMutation creates new mutation for the InquiryKnowledge entity.
func newInquiryKnowledgeMutation(c config, op Op, opts ...inquiryknowledgeOption) *InquiryKnowledgeMutation {
	m := &InquiryKnowledgeMutation{
		config:        c,
		op:            op,
		typ:           TypeInquiryKnowledge,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withInquiryKnowledgeID sets the ID field of the mutation.
func withInquiryKnowledgeID(id int) inquiryknowledgeOption {
	return func(m *InquiryKnowledgeMutation) {
		var (
			err   error
			once  sync.Once
			value *InquiryKnowledge
		)
		m.oldValue = func(ctx context.Context) (*InquiryKnowledge, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().InquiryKnowledge.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withInquiryKnowledge sets the old InquiryKnowledge of the mutation.
func withInquiryKnowledge(node *InquiryKnowledge) inquiryknowledgeOption {
	return func(m *InquiryKnowledgeMutation) {
		m.oldValue = func(context.Context) (*InquiryKnowledge, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m InquiryKnowledgeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m InquiryKnowledgeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("dao: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of InquiryKnowledge entities.
func (m *InquiryKnowledgeMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *InquiryKnowledgeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *InquiryKnowledgeMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().InquiryKnowledge.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetInstruction sets the "instruction" field.
func (m *InquiryKnowledgeMutation) SetInstruction(s string) {
	m.instruction = &s
}

// Instruction returns the value of the "instruction" field in the mutation.
func (m *InquiryKnowledgeMutation) Instruction() (r string, exists bool) {
	v := m.instruction
	if v == nil {
		return
	}
	return *v, true
}

// OldInstruction returns the old "instruction" field's value of the InquiryKnowledge entity.
// If the InquiryKnowledge object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InquiryKnowledgeMutation) OldInstruction(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstruction is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstruction requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstruction: %w", err)
	}
	return oldValue.Instruction, nil
}

// ResetInstruction resets all changes to the "instruction" field.
func (m *InquiryKnowledgeMutation) ResetInstruction() {
	m.instruction = nil
}

// SetInstructionEmbedding sets the "instruction_embedding" field.
func (m *InquiryKnowledgeMutation) SetInstructionEmbedding(pg pgvector.Vector) {
	m.instruction_embedding = &pg
}

// InstructionEmbedding returns the value of the "instruction_embedding" field in the mutation.
func (m *InquiryKnowledgeMutation) InstructionEmbedding() (r pgvector.Vector, exists bool) {
	v := m.instruction_embedding
	if v == nil {
		return
	}
	return *v, true
}

// OldInstructionEmbedding returns the old "instruction_embedding" field's value of the InquiryKnowledge entity.
// If the InquiryKnowledge object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InquiryKnowledgeMutation) OldInstructionEmbedding(ctx context.Context) (v pgvector.Vector, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstructionEmbedding is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstructionEmbedding requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstructionEmbedding: %w", err)
	}
	return oldValue.InstructionEmbedding, nil
}

// ClearInstructionEmbedding clears the value of the "instruction_embedding" field.
func (m *InquiryKnowledgeMutation) ClearInstructionEmbedding() {
	m.instruction_embedding = nil
	m.clearedFields[inquiryknowledge.FieldInstructionEmbedding] = struct{}{}
}

// InstructionEmbeddingCleared returns if the "instruction_embedding" field was cleared in this mutation.
func (m *InquiryKnowledgeMutation) InstructionEmbeddingCleared() bool {
	_, ok := m.clearedFields[inquiryknowledge.FieldInstructionEmbedding]
	return ok
}

// ResetInstructionEmbedding resets all changes to the "instruction_embedding" field.
func (m *InquiryKnowledgeMutation) ResetInstructionEmbedding() {
	m.instruction_embedding = nil
	delete(m.clearedFields, inquiryknowledge.FieldInstructionEmbedding)
}

// SetResponse sets the "response" field.
func (m *InquiryKnowledgeMutation) SetResponse(s string) {
	m.response = &s
}

// Response returns the value of the "response" field in the mutation.
func (m *InquiryKnowledgeMutation) Response() (r string, exists bool) {
	v := m.response
	if v == nil {
		return
	}
	return *v, true
}

// OldResponse returns the old "response" field's value of the InquiryKnowledge entity.
// If the InquiryKnowledge object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InquiryKnowledgeMutation) OldResponse(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResponse is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResponse requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResponse: %w", err)
	}
	return oldValue.Response, nil
}

// ResetResponse resets all changes to the "response" field.
func (m *InquiryKnowledgeMutation) ResetResponse() {
	m.response = nil
}

// SetCategory sets the "category" field.
func (m *InquiryKnowledgeMutation) SetCategory(s string) {
	m.category = &s
}

// Category returns the value of the "category" field in the mutation.
func (m *InquiryKnowledgeMutation) Category() (r string, exists bool) {
	v := m.category
	if v == nil {
		return
	}
	return *v, true
}

// OldCategory returns the old "category" field's value of the InquiryKnowledge entity.
// If the InquiryKnowledge object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InquiryKnowledgeMutation) OldCategory(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCategory is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCategory requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCategory: %w", err)
	}
	return oldValue.Category, nil
}

// ClearCategory clears the value of the "category" field.
func (m *InquiryKnowledgeMutation) ClearCategory() {
	m.category = nil
	m.clearedFields[inquiryknowledge.FieldCategory] = struct{}{}
}

// CategoryCleared returns if the "category" field was cleared in this mutation.
func (m *InquiryKnowledgeMutation) CategoryCleared() bool {
	_, ok := m.clearedFields[inquiryknowledge.FieldCategory]
	return ok
}

// ResetCategory resets all changes to the "category" field.
func (m *InquiryKnowledgeMutation) ResetCategory() {
	m.category = nil
	delete(m.clearedFields, inquiryknowledge.FieldCategory)
}

// SetIntent sets the "intent" field.
func (m *InquiryKnowledgeMutation) SetIntent(s string) {
	m.intent = &s
}

// Intent returns the value of the "intent" field in the mutation.
func (m *InquiryKnowledgeMutation) Intent() (r string, exists bool) {
	v := m.intent
	if v == nil {
		return
	}
	return *v, true
}

// OldIntent returns the old "intent" field's value of the InquiryKnowledge entity.
// If the InquiryKnowledge object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InquiryKnowledgeMutation) OldIntent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIntent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIntent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIntent: %w", err)
	}
	return oldValue.Intent, nil
}

// ClearIntent clears the value of the "intent" field.
func (m *InquiryKnowledgeMutation) ClearIntent() {
	m.intent = nil
	m.clearedFields[inquiryknowledge.FieldIntent] = struct{}{}
}

// IntentCleared returns if the "intent" field was cleared in this mutation.
func (m *InquiryKnowledgeMutation) IntentCleared() bool {
	_, ok := m.clearedFields[inquiryknowledge.FieldIntent]
	return ok
}

// ResetIntent resets all changes to the "intent" field.
func (m *InquiryKnowledgeMutation) ResetIntent() {
	m.intent = nil
	delete(m.clearedFields, inquiryknowledge.FieldIntent)
}

// SetFlags sets the "flags" field.
func (m *InquiryKnowledgeMutation) SetFlags(s string) {
	m.flags = &s
}

// Flags returns the value of the "flags" field in the mutation.
func (m *InquiryKnowledgeMutation) Flags() (r string, exists bool) {
	v := m.flags
	if v == nil {
		return
	}
	return *v, true
}

// OldFlags returns the old "flags" field's value of the InquiryKnowledge entity.
// If the InquiryKnowledge object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InquiryKnowledgeMutation) OldFlags(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFlags is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFlags requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFlags: %w", err)
	}
	return oldValue.Flags, nil
}

// ClearFlags clears the value of the "flags" field.
func (m *InquiryKnowledgeMutation) ClearFlags() {
	m.flags = nil
	m.clearedFields[inquiryknowledge.FieldFlags] = struct{}{}
}

// FlagsCleared returns if the "flags" field was cleared in this mutation.
func (m *InquiryKnowledgeMutation) FlagsCleared() bool {
	_, ok := m.clearedFields[inquiryknowledge.FieldFlags]
	return ok
}

// ResetFlags resets all changes to the "flags" field.
func (m *InquiryKnowledgeMutation) ResetFlags() {
	m.flags = nil
	delete(m.clearedFields, inquiryknowledge.FieldFlags)
}

// SetCreatedAt sets the "created_at" field.
func (m *InquiryKnowledgeMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *InquiryKnowledgeMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the InquiryKnowledge entity.
// If the InquiryKnowledge object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InquiryKnowledgeMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *InquiryKnowledgeMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *InquiryKnowledgeMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *InquiryKnowledgeMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the InquiryKnowledge entity.
// If the InquiryKnowledge object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InquiryKnowledgeMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *InquiryKnowledgeMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the InquiryKnowledgeMutation builder.
func (m *InquiryKnowledgeMutation) Where(ps ...predicate.InquiryKnowledge) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the InquiryKnowledgeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *InquiryKnowledgeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.InquiryKnowledge, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *InquiryKnowledgeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *InquiryKnowledgeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (InquiryKnowledge).
func (m *InquiryKnowledgeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *InquiryKnowledgeMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.instruction != nil {
		fields = append(fields, inquiryknowledge.FieldInstruction)
	}
	if m.instruction_embedding != nil {
		fields = append(fields, inquiryknowledge.FieldInstructionEmbedding)
	}
	if m.response != nil {
		fields = append(fields, inquiryknowledge.FieldResponse)
	}
	if m.category != nil {
		fields = append(fields, inquiryknowledge.FieldCategory)
	}
	if m.intent != nil {
		fields = append(fields, inquiryknowledge.FieldIntent)
	}
	if m.flags != nil {
		fields = append(fields, inquiryknowledge.FieldFlags)
	}
	if m.created_at != nil {
		fields = append(fields, inquiryknowledge.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, inquiryknowledge.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *InquiryKnowledgeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case inquiryknowledge.FieldInstruction:
		return m.Instruction()
	case inquiryknowledge.FieldInstructionEmbedding:
		return m.InstructionEmbedding()
	case inquiryknowledge.FieldResponse:
		return m.Response()
	case inquiryknowledge.FieldCategory:
		return m.Category()
	case inquiryknowledge.FieldIntent:
		return m.Intent()
	case inquiryknowledge.FieldFlags:
		return m.Flags()
	case inquiryknowledge.FieldCreatedAt:
		return m.CreatedAt()
	case inquiryknowledge.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *InquiryKnowledgeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case inquiryknowledge.FieldInstruction:
		return m.OldInstruction(ctx)
	case inquiryknowledge.FieldInstructionEmbedding:
		return m.OldInstructionEmbedding(ctx)
	case inquiryknowledge.FieldResponse:
		return m.OldResponse(ctx)
	case inquiryknowledge.FieldCategory:
		return m.OldCategory(ctx)
	case inquiryknowledge.FieldIntent:
		return m.OldIntent(ctx)
	case inquiryknowledge.FieldFlags:
		return m.OldFlags(ctx)
	case inquiryknowledge.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case inquiryknowledge.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown InquiryKnowledge field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *InquiryKnowledgeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case inquiryknowledge.FieldInstruction:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstruction(v)
		return nil
	case inquiryknowledge.FieldInstructionEmbedding:
		v, ok := value.(pgvector.Vector)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstructionEmbedding(v)
		return nil
	case inquiryknowledge.FieldResponse:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResponse(v)
		return nil
	case inquiryknowledge.FieldCategory:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCategory(v)
		return nil
	case inquiryknowledge.FieldIntent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIntent(v)
		return nil
	case inquiryknowledge.FieldFlags:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFlags(v)
		return nil
	case inquiryknowledge.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case inquiryknowledge.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown InquiryKnowledge field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *InquiryKnowledgeMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *InquiryKnowledgeMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *InquiryKnowledgeMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown InquiryKnowledge numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *InquiryKnowledgeMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(inquiryknowledge.FieldInstructionEmbedding) {
		fields = append(fields, inquiryknowledge.FieldInstructionEmbedding)
	}
	if m.FieldCleared(inquiryknowledge.FieldCategory) {
		fields = append(fields, inquiryknowledge.FieldCategory)
	}
	if m.FieldCleared(inquiryknowledge.FieldIntent) {
		fields = append(fields, inquiryknowledge.FieldIntent)
	}
	if m.FieldCleared(inquiryknowledge.FieldFlags) {
		fields = append(fields, inquiryknowledge.FieldFlags)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *InquiryKnowledgeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *InquiryKnowledgeMutation) ClearField(name string) error {
	switch name {
	case inquiryknowledge.FieldInstructionEmbedding:
		m.ClearInstructionEmbedding()
		return nil
	case inquiryknowledge.FieldCategory:
		m.ClearCategory()
		return nil
	case inquiryknowledge.FieldIntent:
		m.ClearIntent()
		return nil
	case inquiryknowledge.FieldFlags:
		m.ClearFlags()
		return nil
	}
	return fmt.Errorf("unknown InquiryKnowledge nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *InquiryKnowledgeMutation) ResetField(name string) error {
	switch name {
	case inquiryknowledge.FieldInstruction:
		m.ResetInstruction()
		return nil
	case inquiryknowledge.FieldInstructionEmbedding:
		m.ResetInstructionEmbedding()
		return nil
	case inquiryknowledge.FieldResponse:
		m.ResetResponse()
		return nil
	case inquiryknowledge.FieldCategory:
		m.ResetCategory()
		return nil
	case inquiryknowledge.FieldIntent:
		m.ResetIntent()
		return nil
	case inquiryknowledge.FieldFlags:
		m.ResetFlags()
		return nil
	case inquiryknowledge.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case inquiryknowledge.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown InquiryKnowledge field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *InquiryKnowledgeMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *InquiryKnowledgeMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *InquiryKnowledgeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *InquiryKnowledgeMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *InquiryKnowledgeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *InquiryKnowledgeMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *InquiryKnowledgeMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown InquiryKnowledge unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *InquiryKnowledgeMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown InquiryKnowledge edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	email         *string
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*User, error)
	predicates    []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("dao: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *UserMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *UserMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *UserMutation) ResetName() {
	m.name = nil
}

// SetEmail sets the "email" field.
func (m *UserMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *UserMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *UserMutation) ResetEmail() {
	m.email = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *UserMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, user.FieldName)
	}
	if m.email != nil {
		fields = append(fields, user.FieldEmail)
	}
	if m.created_at != nil {
		fields = append(fields, user.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldName:
		return m.Name()
	case user.FieldEmail:
		return m.Email()
	case user.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldName:
		return m.OldName(ctx)
	case user.FieldEmail:
		return m.OldEmail(ctx)
	case user.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case user.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case user.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldName:
		m.ResetName()
		return nil
	case user.FieldEmail:
		m.ResetEmail()
		return nil
	case user.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown User edge %s", name)
}
