// Code generated by ent, DO NOT EDIT.

package dao

import (
	"time"

	"github.com/wonjinsin/simple-chatbot/internal/repository/postgres/dao/inquiryknowledge"
	"github.com/wonjinsin/simple-chatbot/internal/repository/postgres/dao/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	inquiryknowledgeFields := schema.InquiryKnowledge{}.Fields()
	_ = inquiryknowledgeFields
	// inquiryknowledgeDescInstruction is the schema descriptor for instruction field.
	inquiryknowledgeDescInstruction := inquiryknowledgeFields[1].Descriptor()
	// inquiryknowledge.InstructionValidator is a validator for the "instruction" field. It is called by the builders before save.
	inquiryknowledge.InstructionValidator = inquiryknowledgeDescInstruction.Validators[0].(func(string) error)
	// inquiryknowledgeDescResponse is the schema descriptor for response field.
	inquiryknowledgeDescResponse := inquiryknowledgeFields[3].Descriptor()
	// inquiryknowledge.ResponseValidator is a validator for the "response" field. It is called by the builders before save.
	inquiryknowledge.ResponseValidator = inquiryknowledgeDescResponse.Validators[0].(func(string) error)
	// inquiryknowledgeDescCreatedAt is the schema descriptor for created_at field.
	inquiryknowledgeDescCreatedAt := inquiryknowledgeFields[7].Descriptor()
	// inquiryknowledge.DefaultCreatedAt holds the default value on creation for the created_at field.
	inquiryknowledge.DefaultCreatedAt = inquiryknowledgeDescCreatedAt.Default.(func() time.Time)
	// inquiryknowledgeDescUpdatedAt is the schema descriptor for updated_at field.
	inquiryknowledgeDescUpdatedAt := inquiryknowledgeFields[8].Descriptor()
	// inquiryknowledge.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	inquiryknowledge.DefaultUpdatedAt = inquiryknowledgeDescUpdatedAt.Default.(func() time.Time)
	// inquiryknowledge.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	inquiryknowledge.UpdateDefaultUpdatedAt = inquiryknowledgeDescUpdatedAt.UpdateDefault.(func() time.Time)
}
