// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InquiryKnowledgesColumns holds the columns for the "inquiry_knowledges" table.
	InquiryKnowledgesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "instruction", Type: field.TypeString, Size: 2147483647},
		{Name: "instruction_embedding", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "vector(1536)"}},
		{Name: "response", Type: field.TypeString, Size: 2147483647},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "intent", Type: field.TypeString, Nullable: true},
		{Name: "flags", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// InquiryKnowledgesTable holds the schema information for the "inquiry_knowledges" table.
	InquiryKnowledgesTable = &schema.Table{
		Name:       "inquiry_knowledges",
		Columns:    InquiryKnowledgesColumns,
		PrimaryKey: []*schema.Column{InquiryKnowledgesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "inquiryknowledge_instruction_embedding",
				Unique:  false,
				Columns: []*schema.Column{InquiryKnowledgesColumns[2]},
				Annotation: &entsql.IndexAnnotation{
					OpClass: "vector_cosine_ops",
					Type:    "hnsw",
				},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InquiryKnowledgesTable,
	}
)

func init() {
	InquiryKnowledgesTable.Annotation = &entsql.Annotation{
		Table: "inquiry_knowledges",
	}
}
