// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	pgvector "github.com/pgvector/pgvector-go"
	"github.com/wonjinsin/simple-chatbot/internal/repository/postgres/dao/ent/inquiryknowledge"
)

// InquiryKnowledge is the model entity for the InquiryKnowledge schema.
type InquiryKnowledge struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Instruction holds the value of the "instruction" field.
	Instruction string `json:"instruction,omitempty"`
	// InstructionEmbedding holds the value of the "instruction_embedding" field.
	InstructionEmbedding pgvector.Vector `json:"instruction_embedding,omitempty"`
	// Response holds the value of the "response" field.
	Response string `json:"response,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Intent holds the value of the "intent" field.
	Intent string `json:"intent,omitempty"`
	// Flags holds the value of the "flags" field.
	Flags string `json:"flags,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InquiryKnowledge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inquiryknowledge.FieldInstructionEmbedding:
			values[i] = new(pgvector.Vector)
		case inquiryknowledge.FieldID:
			values[i] = new(sql.NullInt64)
		case inquiryknowledge.FieldInstruction, inquiryknowledge.FieldResponse, inquiryknowledge.FieldCategory, inquiryknowledge.FieldIntent, inquiryknowledge.FieldFlags:
			values[i] = new(sql.NullString)
		case inquiryknowledge.FieldCreatedAt, inquiryknowledge.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InquiryKnowledge fields.
func (_m *InquiryKnowledge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inquiryknowledge.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case inquiryknowledge.FieldInstruction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field instruction", values[i])
			} else if value.Valid {
				_m.Instruction = value.String
			}
		case inquiryknowledge.FieldInstructionEmbedding:
			if value, ok := values[i].(*pgvector.Vector); !ok {
				return fmt.Errorf("unexpected type %T for field instruction_embedding", values[i])
			} else if value != nil {
				_m.InstructionEmbedding = *value
			}
		case inquiryknowledge.FieldResponse:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response", values[i])
			} else if value.Valid {
				_m.Response = value.String
			}
		case inquiryknowledge.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case inquiryknowledge.FieldIntent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field intent", values[i])
			} else if value.Valid {
				_m.Intent = value.String
			}
		case inquiryknowledge.FieldFlags:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field flags", values[i])
			} else if value.Valid {
				_m.Flags = value.String
			}
		case inquiryknowledge.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case inquiryknowledge.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InquiryKnowledge.
// This includes values selected through modifiers, order, etc.
func (_m *InquiryKnowledge) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InquiryKnowledge.
// Note that you need to call InquiryKnowledge.Unwrap() before calling this method if this InquiryKnowledge
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InquiryKnowledge) Update() *InquiryKnowledgeUpdateOne {
	return NewInquiryKnowledgeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InquiryKnowledge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InquiryKnowledge) Unwrap() *InquiryKnowledge {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InquiryKnowledge is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InquiryKnowledge) String() string {
	var builder strings.Builder
	builder.WriteString("InquiryKnowledge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("instruction=")
	builder.WriteString(_m.Instruction)
	builder.WriteString(", ")
	builder.WriteString("instruction_embedding=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstructionEmbedding))
	builder.WriteString(", ")
	builder.WriteString("response=")
	builder.WriteString(_m.Response)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("intent=")
	builder.WriteString(_m.Intent)
	builder.WriteString(", ")
	builder.WriteString("flags=")
	builder.WriteString(_m.Flags)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InquiryKnowledges is a parsable slice of InquiryKnowledge.
type InquiryKnowledges []*InquiryKnowledge
