// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	pgvector "github.com/pgvector/pgvector-go"
	"github.com/wonjinsin/simple-chatbot/internal/repository/postgres/dao/ent/inquiryknowledge"
)

// InquiryKnowledgeCreate is the builder for creating a InquiryKnowledge entity.
type InquiryKnowledgeCreate struct {
	config
	mutation *InquiryKnowledgeMutation
	hooks    []Hook
}

// SetInstruction sets the "instruction" field.
func (_c *InquiryKnowledgeCreate) SetInstruction(v string) *InquiryKnowledgeCreate {
	_c.mutation.SetInstruction(v)
	return _c
}

// SetInstructionEmbedding sets the "instruction_embedding" field.
func (_c *InquiryKnowledgeCreate) SetInstructionEmbedding(v pgvector.Vector) *InquiryKnowledgeCreate {
	_c.mutation.SetInstructionEmbedding(v)
	return _c
}

// SetNillableInstructionEmbedding sets the "instruction_embedding" field if the given value is not nil.
func (_c *InquiryKnowledgeCreate) SetNillableInstructionEmbedding(v *pgvector.Vector) *InquiryKnowledgeCreate {
	if v != nil {
		_c.SetInstructionEmbedding(*v)
	}
	return _c
}

// SetResponse sets the "response" field.
func (_c *InquiryKnowledgeCreate) SetResponse(v string) *InquiryKnowledgeCreate {
	_c.mutation.SetResponse(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *InquiryKnowledgeCreate) SetCategory(v string) *InquiryKnowledgeCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *InquiryKnowledgeCreate) SetNillableCategory(v *string) *InquiryKnowledgeCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetIntent sets the "intent" field.
func (_c *InquiryKnowledgeCreate) SetIntent(v string) *InquiryKnowledgeCreate {
	_c.mutation.SetIntent(v)
	return _c
}

// SetNillableIntent sets the "intent" field if the given value is not nil.
func (_c *InquiryKnowledgeCreate) SetNillableIntent(v *string) *InquiryKnowledgeCreate {
	if v != nil {
		_c.SetIntent(*v)
	}
	return _c
}

// SetFlags sets the "flags" field.
func (_c *InquiryKnowledgeCreate) SetFlags(v string) *InquiryKnowledgeCreate {
	_c.mutation.SetFlags(v)
	return _c
}

// SetNillableFlags sets the "flags" field if the given value is not nil.
func (_c *InquiryKnowledgeCreate) SetNillableFlags(v *string) *InquiryKnowledgeCreate {
	if v != nil {
		_c.SetFlags(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InquiryKnowledgeCreate) SetCreatedAt(v time.Time) *InquiryKnowledgeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InquiryKnowledgeCreate) SetNillableCreatedAt(v *time.Time) *InquiryKnowledgeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InquiryKnowledgeCreate) SetUpdatedAt(v time.Time) *InquiryKnowledgeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InquiryKnowledgeCreate) SetNillableUpdatedAt(v *time.Time) *InquiryKnowledgeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InquiryKnowledgeCreate) SetID(v int) *InquiryKnowledgeCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the InquiryKnowledgeMutation object of the builder.
func (_c *InquiryKnowledgeCreate) Mutation() *InquiryKnowledgeMutation {
	return _c.mutation
}

// Save creates the InquiryKnowledge in the database.
func (_c *InquiryKnowledgeCreate) Save(ctx context.Context) (*InquiryKnowledge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InquiryKnowledgeCreate) SaveX(ctx context.Context) *InquiryKnowledge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InquiryKnowledgeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InquiryKnowledgeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InquiryKnowledgeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := inquiryknowledge.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := inquiryknowledge.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InquiryKnowledgeCreate) check() error {
	if _, ok := _c.mutation.Instruction(); !ok {
		return &ValidationError{Name: "instruction", err: errors.New(`ent: missing required field "InquiryKnowledge.instruction"`)}
	}
	if v, ok := _c.mutation.Instruction(); ok {
		if err := inquiryknowledge.InstructionValidator(v); err != nil {
			return &ValidationError{Name: "instruction", err: fmt.Errorf(`ent: validator failed for field "InquiryKnowledge.instruction": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Response(); !ok {
		return &ValidationError{Name: "response", err: errors.New(`ent: missing required field "InquiryKnowledge.response"`)}
	}
	if v, ok := _c.mutation.Response(); ok {
		if err := inquiryknowledge.ResponseValidator(v); err != nil {
			return &ValidationError{Name: "response", err: fmt.Errorf(`ent: validator failed for field "InquiryKnowledge.response": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InquiryKnowledge.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InquiryKnowledge.updated_at"`)}
	}
	return nil
}

func (_c *InquiryKnowledgeCreate) sqlSave(ctx context.Context) (*InquiryKnowledge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InquiryKnowledgeCreate) createSpec() (*InquiryKnowledge, *sqlgraph.CreateSpec) {
	var (
		_node = &InquiryKnowledge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inquiryknowledge.Table, sqlgraph.NewFieldSpec(inquiryknowledge.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Instruction(); ok {
		_spec.SetField(inquiryknowledge.FieldInstruction, field.TypeString, value)
		_node.Instruction = value
	}
	if value, ok := _c.mutation.InstructionEmbedding(); ok {
		_spec.SetField(inquiryknowledge.FieldInstructionEmbedding, field.TypeOther, value)
		_node.InstructionEmbedding = value
	}
	if value, ok := _c.mutation.Response(); ok {
		_spec.SetField(inquiryknowledge.FieldResponse, field.TypeString, value)
		_node.Response = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(inquiryknowledge.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Intent(); ok {
		_spec.SetField(inquiryknowledge.FieldIntent, field.TypeString, value)
		_node.Intent = value
	}
	if value, ok := _c.mutation.Flags(); ok {
		_spec.SetField(inquiryknowledge.FieldFlags, field.TypeString, value)
		_node.Flags = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(inquiryknowledge.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(inquiryknowledge.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// InquiryKnowledgeCreateBulk is the builder for creating many InquiryKnowledge entities in bulk.
type InquiryKnowledgeCreateBulk struct {
	config
	err      error
	builders []*InquiryKnowledgeCreate
}

// Save creates the InquiryKnowledge entities in the database.
func (_c *InquiryKnowledgeCreateBulk) Save(ctx context.Context) ([]*InquiryKnowledge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InquiryKnowledge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InquiryKnowledgeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InquiryKnowledgeCreateBulk) SaveX(ctx context.Context) []*InquiryKnowledge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InquiryKnowledgeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InquiryKnowledgeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
