// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	pgvector "github.com/pgvector/pgvector-go"
	"github.com/wonjinsin/simple-chatbot/internal/repository/postgres/dao/ent/inquiryknowledge"
	"github.com/wonjinsin/simple-chatbot/internal/repository/postgres/dao/ent/predicate"
)

// InquiryKnowledgeUpdate is the builder for updating InquiryKnowledge entities.
type InquiryKnowledgeUpdate struct {
	config
	hooks    []Hook
	mutation *InquiryKnowledgeMutation
}

// Where appends a list predicates to the InquiryKnowledgeUpdate builder.
func (_u *InquiryKnowledgeUpdate) Where(ps ...predicate.InquiryKnowledge) *InquiryKnowledgeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInstruction sets the "instruction" field.
func (_u *InquiryKnowledgeUpdate) SetInstruction(v string) *InquiryKnowledgeUpdate {
	_u.mutation.SetInstruction(v)
	return _u
}

// SetNillableInstruction sets the "instruction" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdate) SetNillableInstruction(v *string) *InquiryKnowledgeUpdate {
	if v != nil {
		_u.SetInstruction(*v)
	}
	return _u
}

// SetInstructionEmbedding sets the "instruction_embedding" field.
func (_u *InquiryKnowledgeUpdate) SetInstructionEmbedding(v pgvector.Vector) *InquiryKnowledgeUpdate {
	_u.mutation.SetInstructionEmbedding(v)
	return _u
}

// SetNillableInstructionEmbedding sets the "instruction_embedding" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdate) SetNillableInstructionEmbedding(v *pgvector.Vector) *InquiryKnowledgeUpdate {
	if v != nil {
		_u.SetInstructionEmbedding(*v)
	}
	return _u
}

// ClearInstructionEmbedding clears the value of the "instruction_embedding" field.
func (_u *InquiryKnowledgeUpdate) ClearInstructionEmbedding() *InquiryKnowledgeUpdate {
	_u.mutation.ClearInstructionEmbedding()
	return _u
}

// SetResponse sets the "response" field.
func (_u *InquiryKnowledgeUpdate) SetResponse(v string) *InquiryKnowledgeUpdate {
	_u.mutation.SetResponse(v)
	return _u
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdate) SetNillableResponse(v *string) *InquiryKnowledgeUpdate {
	if v != nil {
		_u.SetResponse(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *InquiryKnowledgeUpdate) SetCategory(v string) *InquiryKnowledgeUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdate) SetNillableCategory(v *string) *InquiryKnowledgeUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *InquiryKnowledgeUpdate) ClearCategory() *InquiryKnowledgeUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetIntent sets the "intent" field.
func (_u *InquiryKnowledgeUpdate) SetIntent(v string) *InquiryKnowledgeUpdate {
	_u.mutation.SetIntent(v)
	return _u
}

// SetNillableIntent sets the "intent" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdate) SetNillableIntent(v *string) *InquiryKnowledgeUpdate {
	if v != nil {
		_u.SetIntent(*v)
	}
	return _u
}

// ClearIntent clears the value of the "intent" field.
func (_u *InquiryKnowledgeUpdate) ClearIntent() *InquiryKnowledgeUpdate {
	_u.mutation.ClearIntent()
	return _u
}

// SetFlags sets the "flags" field.
func (_u *InquiryKnowledgeUpdate) SetFlags(v string) *InquiryKnowledgeUpdate {
	_u.mutation.SetFlags(v)
	return _u
}

// SetNillableFlags sets the "flags" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdate) SetNillableFlags(v *string) *InquiryKnowledgeUpdate {
	if v != nil {
		_u.SetFlags(*v)
	}
	return _u
}

// ClearFlags clears the value of the "flags" field.
func (_u *InquiryKnowledgeUpdate) ClearFlags() *InquiryKnowledgeUpdate {
	_u.mutation.ClearFlags()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InquiryKnowledgeUpdate) SetUpdatedAt(v time.Time) *InquiryKnowledgeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InquiryKnowledgeMutation object of the builder.
func (_u *InquiryKnowledgeUpdate) Mutation() *InquiryKnowledgeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InquiryKnowledgeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InquiryKnowledgeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InquiryKnowledgeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InquiryKnowledgeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InquiryKnowledgeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := inquiryknowledge.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InquiryKnowledgeUpdate) check() error {
	if v, ok := _u.mutation.Instruction(); ok {
		if err := inquiryknowledge.InstructionValidator(v); err != nil {
			return &ValidationError{Name: "instruction", err: fmt.Errorf(`ent: validator failed for field "InquiryKnowledge.instruction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Response(); ok {
		if err := inquiryknowledge.ResponseValidator(v); err != nil {
			return &ValidationError{Name: "response", err: fmt.Errorf(`ent: validator failed for field "InquiryKnowledge.response": %w`, err)}
		}
	}
	return nil
}

func (_u *InquiryKnowledgeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inquiryknowledge.Table, inquiryknowledge.Columns, sqlgraph.NewFieldSpec(inquiryknowledge.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Instruction(); ok {
		_spec.SetField(inquiryknowledge.FieldInstruction, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstructionEmbedding(); ok {
		_spec.SetField(inquiryknowledge.FieldInstructionEmbedding, field.TypeOther, value)
	}
	if _u.mutation.InstructionEmbeddingCleared() {
		_spec.ClearField(inquiryknowledge.FieldInstructionEmbedding, field.TypeOther)
	}
	if value, ok := _u.mutation.Response(); ok {
		_spec.SetField(inquiryknowledge.FieldResponse, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(inquiryknowledge.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(inquiryknowledge.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Intent(); ok {
		_spec.SetField(inquiryknowledge.FieldIntent, field.TypeString, value)
	}
	if _u.mutation.IntentCleared() {
		_spec.ClearField(inquiryknowledge.FieldIntent, field.TypeString)
	}
	if value, ok := _u.mutation.Flags(); ok {
		_spec.SetField(inquiryknowledge.FieldFlags, field.TypeString, value)
	}
	if _u.mutation.FlagsCleared() {
		_spec.ClearField(inquiryknowledge.FieldFlags, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(inquiryknowledge.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inquiryknowledge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InquiryKnowledgeUpdateOne is the builder for updating a single InquiryKnowledge entity.
type InquiryKnowledgeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InquiryKnowledgeMutation
}

// SetInstruction sets the "instruction" field.
func (_u *InquiryKnowledgeUpdateOne) SetInstruction(v string) *InquiryKnowledgeUpdateOne {
	_u.mutation.SetInstruction(v)
	return _u
}

// SetNillableInstruction sets the "instruction" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdateOne) SetNillableInstruction(v *string) *InquiryKnowledgeUpdateOne {
	if v != nil {
		_u.SetInstruction(*v)
	}
	return _u
}

// SetInstructionEmbedding sets the "instruction_embedding" field.
func (_u *InquiryKnowledgeUpdateOne) SetInstructionEmbedding(v pgvector.Vector) *InquiryKnowledgeUpdateOne {
	_u.mutation.SetInstructionEmbedding(v)
	return _u
}

// SetNillableInstructionEmbedding sets the "instruction_embedding" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdateOne) SetNillableInstructionEmbedding(v *pgvector.Vector) *InquiryKnowledgeUpdateOne {
	if v != nil {
		_u.SetInstructionEmbedding(*v)
	}
	return _u
}

// ClearInstructionEmbedding clears the value of the "instruction_embedding" field.
func (_u *InquiryKnowledgeUpdateOne) ClearInstructionEmbedding() *InquiryKnowledgeUpdateOne {
	_u.mutation.ClearInstructionEmbedding()
	return _u
}

// SetResponse sets the "response" field.
func (_u *InquiryKnowledgeUpdateOne) SetResponse(v string) *InquiryKnowledgeUpdateOne {
	_u.mutation.SetResponse(v)
	return _u
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdateOne) SetNillableResponse(v *string) *InquiryKnowledgeUpdateOne {
	if v != nil {
		_u.SetResponse(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *InquiryKnowledgeUpdateOne) SetCategory(v string) *InquiryKnowledgeUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdateOne) SetNillableCategory(v *string) *InquiryKnowledgeUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *InquiryKnowledgeUpdateOne) ClearCategory() *InquiryKnowledgeUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetIntent sets the "intent" field.
func (_u *InquiryKnowledgeUpdateOne) SetIntent(v string) *InquiryKnowledgeUpdateOne {
	_u.mutation.SetIntent(v)
	return _u
}

// SetNillableIntent sets the "intent" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdateOne) SetNillableIntent(v *string) *InquiryKnowledgeUpdateOne {
	if v != nil {
		_u.SetIntent(*v)
	}
	return _u
}

// ClearIntent clears the value of the "intent" field.
func (_u *InquiryKnowledgeUpdateOne) ClearIntent() *InquiryKnowledgeUpdateOne {
	_u.mutation.ClearIntent()
	return _u
}

// SetFlags sets the "flags" field.
func (_u *InquiryKnowledgeUpdateOne) SetFlags(v string) *InquiryKnowledgeUpdateOne {
	_u.mutation.SetFlags(v)
	return _u
}

// SetNillableFlags sets the "flags" field if the given value is not nil.
func (_u *InquiryKnowledgeUpdateOne) SetNillableFlags(v *string) *InquiryKnowledgeUpdateOne {
	if v != nil {
		_u.SetFlags(*v)
	}
	return _u
}

// ClearFlags clears the value of the "flags" field.
func (_u *InquiryKnowledgeUpdateOne) ClearFlags() *InquiryKnowledgeUpdateOne {
	_u.mutation.ClearFlags()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InquiryKnowledgeUpdateOne) SetUpdatedAt(v time.Time) *InquiryKnowledgeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InquiryKnowledgeMutation object of the builder.
func (_u *InquiryKnowledgeUpdateOne) Mutation() *InquiryKnowledgeMutation {
	return _u.mutation
}

// Where appends a list predicates to the InquiryKnowledgeUpdate builder.
func (_u *InquiryKnowledgeUpdateOne) Where(ps ...predicate.InquiryKnowledge) *InquiryKnowledgeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InquiryKnowledgeUpdateOne) Select(field string, fields ...string) *InquiryKnowledgeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InquiryKnowledge entity.
func (_u *InquiryKnowledgeUpdateOne) Save(ctx context.Context) (*InquiryKnowledge, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InquiryKnowledgeUpdateOne) SaveX(ctx context.Context) *InquiryKnowledge {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InquiryKnowledgeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InquiryKnowledgeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InquiryKnowledgeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := inquiryknowledge.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InquiryKnowledgeUpdateOne) check() error {
	if v, ok := _u.mutation.Instruction(); ok {
		if err := inquiryknowledge.InstructionValidator(v); err != nil {
			return &ValidationError{Name: "instruction", err: fmt.Errorf(`ent: validator failed for field "InquiryKnowledge.instruction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Response(); ok {
		if err := inquiryknowledge.ResponseValidator(v); err != nil {
			return &ValidationError{Name: "response", err: fmt.Errorf(`ent: validator failed for field "InquiryKnowledge.response": %w`, err)}
		}
	}
	return nil
}

func (_u *InquiryKnowledgeUpdateOne) sqlSave(ctx context.Context) (_node *InquiryKnowledge, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inquiryknowledge.Table, inquiryknowledge.Columns, sqlgraph.NewFieldSpec(inquiryknowledge.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InquiryKnowledge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inquiryknowledge.FieldID)
		for _, f := range fields {
			if !inquiryknowledge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != inquiryknowledge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Instruction(); ok {
		_spec.SetField(inquiryknowledge.FieldInstruction, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstructionEmbedding(); ok {
		_spec.SetField(inquiryknowledge.FieldInstructionEmbedding, field.TypeOther, value)
	}
	if _u.mutation.InstructionEmbeddingCleared() {
		_spec.ClearField(inquiryknowledge.FieldInstructionEmbedding, field.TypeOther)
	}
	if value, ok := _u.mutation.Response(); ok {
		_spec.SetField(inquiryknowledge.FieldResponse, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(inquiryknowledge.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(inquiryknowledge.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Intent(); ok {
		_spec.SetField(inquiryknowledge.FieldIntent, field.TypeString, value)
	}
	if _u.mutation.IntentCleared() {
		_spec.ClearField(inquiryknowledge.FieldIntent, field.TypeString)
	}
	if value, ok := _u.mutation.Flags(); ok {
		_spec.SetField(inquiryknowledge.FieldFlags, field.TypeString, value)
	}
	if _u.mutation.FlagsCleared() {
		_spec.ClearField(inquiryknowledge.FieldFlags, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(inquiryknowledge.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &InquiryKnowledge{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inquiryknowledge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
