// Code generated by ent, DO NOT EDIT.

package inquiryknowledge

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the inquiryknowledge type in the database.
	Label = "inquiry_knowledge"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInstruction holds the string denoting the instruction field in the database.
	FieldInstruction = "instruction"
	// FieldInstructionEmbedding holds the string denoting the instruction_embedding field in the database.
	FieldInstructionEmbedding = "instruction_embedding"
	// FieldResponse holds the string denoting the response field in the database.
	FieldResponse = "response"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldIntent holds the string denoting the intent field in the database.
	FieldIntent = "intent"
	// FieldFlags holds the string denoting the flags field in the database.
	FieldFlags = "flags"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the inquiryknowledge in the database.
	Table = "inquiry_knowledges"
)

// Columns holds all SQL columns for inquiryknowledge fields.
var Columns = []string{
	FieldID,
	FieldInstruction,
	FieldInstructionEmbedding,
	FieldResponse,
	FieldCategory,
	FieldIntent,
	FieldFlags,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// InstructionValidator is a validator for the "instruction" field. It is called by the builders before save.
	InstructionValidator func(string) error
	// ResponseValidator is a validator for the "response" field. It is called by the builders before save.
	ResponseValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the InquiryKnowledge queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInstruction orders the results by the instruction field.
func ByInstruction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstruction, opts...).ToFunc()
}

// ByInstructionEmbedding orders the results by the instruction_embedding field.
func ByInstructionEmbedding(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstructionEmbedding, opts...).ToFunc()
}

// ByResponse orders the results by the response field.
func ByResponse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponse, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByIntent orders the results by the intent field.
func ByIntent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntent, opts...).ToFunc()
}

// ByFlags orders the results by the flags field.
func ByFlags(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlags, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
