// Code generated by ent, DO NOT EDIT.

package inquiryknowledge

import (
	"time"

	"entgo.io/ent/dialect/sql"
	pgvector "github.com/pgvector/pgvector-go"
	"github.com/wonjinsin/simple-chatbot/internal/repository/postgres/dao/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLTE(FieldID, id))
}

// Instruction applies equality check predicate on the "instruction" field. It's identical to InstructionEQ.
func Instruction(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldInstruction, v))
}

// InstructionEmbedding applies equality check predicate on the "instruction_embedding" field. It's identical to InstructionEmbeddingEQ.
func InstructionEmbedding(v pgvector.Vector) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldInstructionEmbedding, v))
}

// Response applies equality check predicate on the "response" field. It's identical to ResponseEQ.
func Response(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldResponse, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldCategory, v))
}

// Intent applies equality check predicate on the "intent" field. It's identical to IntentEQ.
func Intent(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldIntent, v))
}

// Flags applies equality check predicate on the "flags" field. It's identical to FlagsEQ.
func Flags(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldFlags, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldUpdatedAt, v))
}

// InstructionEQ applies the EQ predicate on the "instruction" field.
func InstructionEQ(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldInstruction, v))
}

// InstructionNEQ applies the NEQ predicate on the "instruction" field.
func InstructionNEQ(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNEQ(FieldInstruction, v))
}

// InstructionIn applies the In predicate on the "instruction" field.
func InstructionIn(vs ...string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIn(FieldInstruction, vs...))
}

// InstructionNotIn applies the NotIn predicate on the "instruction" field.
func InstructionNotIn(vs ...string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotIn(FieldInstruction, vs...))
}

// InstructionGT applies the GT predicate on the "instruction" field.
func InstructionGT(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGT(FieldInstruction, v))
}

// InstructionGTE applies the GTE predicate on the "instruction" field.
func InstructionGTE(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGTE(FieldInstruction, v))
}

// InstructionLT applies the LT predicate on the "instruction" field.
func InstructionLT(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLT(FieldInstruction, v))
}

// InstructionLTE applies the LTE predicate on the "instruction" field.
func InstructionLTE(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLTE(FieldInstruction, v))
}

// InstructionContains applies the Contains predicate on the "instruction" field.
func InstructionContains(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldContains(FieldInstruction, v))
}

// InstructionHasPrefix applies the HasPrefix predicate on the "instruction" field.
func InstructionHasPrefix(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldHasPrefix(FieldInstruction, v))
}

// InstructionHasSuffix applies the HasSuffix predicate on the "instruction" field.
func InstructionHasSuffix(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldHasSuffix(FieldInstruction, v))
}

// InstructionEqualFold applies the EqualFold predicate on the "instruction" field.
func InstructionEqualFold(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEqualFold(FieldInstruction, v))
}

// InstructionContainsFold applies the ContainsFold predicate on the "instruction" field.
func InstructionContainsFold(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldContainsFold(FieldInstruction, v))
}

// InstructionEmbeddingEQ applies the EQ predicate on the "instruction_embedding" field.
func InstructionEmbeddingEQ(v pgvector.Vector) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldInstructionEmbedding, v))
}

// InstructionEmbeddingNEQ applies the NEQ predicate on the "instruction_embedding" field.
func InstructionEmbeddingNEQ(v pgvector.Vector) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNEQ(FieldInstructionEmbedding, v))
}

// InstructionEmbeddingIn applies the In predicate on the "instruction_embedding" field.
func InstructionEmbeddingIn(vs ...pgvector.Vector) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIn(FieldInstructionEmbedding, vs...))
}

// InstructionEmbeddingNotIn applies the NotIn predicate on the "instruction_embedding" field.
func InstructionEmbeddingNotIn(vs ...pgvector.Vector) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotIn(FieldInstructionEmbedding, vs...))
}

// InstructionEmbeddingGT applies the GT predicate on the "instruction_embedding" field.
func InstructionEmbeddingGT(v pgvector.Vector) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGT(FieldInstructionEmbedding, v))
}

// InstructionEmbeddingGTE applies the GTE predicate on the "instruction_embedding" field.
func InstructionEmbeddingGTE(v pgvector.Vector) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGTE(FieldInstructionEmbedding, v))
}

// InstructionEmbeddingLT applies the LT predicate on the "instruction_embedding" field.
func InstructionEmbeddingLT(v pgvector.Vector) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLT(FieldInstructionEmbedding, v))
}

// InstructionEmbeddingLTE applies the LTE predicate on the "instruction_embedding" field.
func InstructionEmbeddingLTE(v pgvector.Vector) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLTE(FieldInstructionEmbedding, v))
}

// InstructionEmbeddingIsNil applies the IsNil predicate on the "instruction_embedding" field.
func InstructionEmbeddingIsNil() predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIsNull(FieldInstructionEmbedding))
}

// InstructionEmbeddingNotNil applies the NotNil predicate on the "instruction_embedding" field.
func InstructionEmbeddingNotNil() predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotNull(FieldInstructionEmbedding))
}

// ResponseEQ applies the EQ predicate on the "response" field.
func ResponseEQ(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldResponse, v))
}

// ResponseNEQ applies the NEQ predicate on the "response" field.
func ResponseNEQ(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNEQ(FieldResponse, v))
}

// ResponseIn applies the In predicate on the "response" field.
func ResponseIn(vs ...string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIn(FieldResponse, vs...))
}

// ResponseNotIn applies the NotIn predicate on the "response" field.
func ResponseNotIn(vs ...string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotIn(FieldResponse, vs...))
}

// ResponseGT applies the GT predicate on the "response" field.
func ResponseGT(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGT(FieldResponse, v))
}

// ResponseGTE applies the GTE predicate on the "response" field.
func ResponseGTE(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGTE(FieldResponse, v))
}

// ResponseLT applies the LT predicate on the "response" field.
func ResponseLT(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLT(FieldResponse, v))
}

// ResponseLTE applies the LTE predicate on the "response" field.
func ResponseLTE(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLTE(FieldResponse, v))
}

// ResponseContains applies the Contains predicate on the "response" field.
func ResponseContains(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldContains(FieldResponse, v))
}

// ResponseHasPrefix applies the HasPrefix predicate on the "response" field.
func ResponseHasPrefix(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldHasPrefix(FieldResponse, v))
}

// ResponseHasSuffix applies the HasSuffix predicate on the "response" field.
func ResponseHasSuffix(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldHasSuffix(FieldResponse, v))
}

// ResponseEqualFold applies the EqualFold predicate on the "response" field.
func ResponseEqualFold(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEqualFold(FieldResponse, v))
}

// ResponseContainsFold applies the ContainsFold predicate on the "response" field.
func ResponseContainsFold(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldContainsFold(FieldResponse, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryIsNil applies the IsNil predicate on the "category" field.
func CategoryIsNil() predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIsNull(FieldCategory))
}

// CategoryNotNil applies the NotNil predicate on the "category" field.
func CategoryNotNil() predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotNull(FieldCategory))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldContainsFold(FieldCategory, v))
}

// IntentEQ applies the EQ predicate on the "intent" field.
func IntentEQ(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldIntent, v))
}

// IntentNEQ applies the NEQ predicate on the "intent" field.
func IntentNEQ(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNEQ(FieldIntent, v))
}

// IntentIn applies the In predicate on the "intent" field.
func IntentIn(vs ...string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIn(FieldIntent, vs...))
}

// IntentNotIn applies the NotIn predicate on the "intent" field.
func IntentNotIn(vs ...string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotIn(FieldIntent, vs...))
}

// IntentGT applies the GT predicate on the "intent" field.
func IntentGT(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGT(FieldIntent, v))
}

// IntentGTE applies the GTE predicate on the "intent" field.
func IntentGTE(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGTE(FieldIntent, v))
}

// IntentLT applies the LT predicate on the "intent" field.
func IntentLT(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLT(FieldIntent, v))
}

// IntentLTE applies the LTE predicate on the "intent" field.
func IntentLTE(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLTE(FieldIntent, v))
}

// IntentContains applies the Contains predicate on the "intent" field.
func IntentContains(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldContains(FieldIntent, v))
}

// IntentHasPrefix applies the HasPrefix predicate on the "intent" field.
func IntentHasPrefix(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldHasPrefix(FieldIntent, v))
}

// IntentHasSuffix applies the HasSuffix predicate on the "intent" field.
func IntentHasSuffix(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldHasSuffix(FieldIntent, v))
}

// IntentIsNil applies the IsNil predicate on the "intent" field.
func IntentIsNil() predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIsNull(FieldIntent))
}

// IntentNotNil applies the NotNil predicate on the "intent" field.
func IntentNotNil() predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotNull(FieldIntent))
}

// IntentEqualFold applies the EqualFold predicate on the "intent" field.
func IntentEqualFold(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEqualFold(FieldIntent, v))
}

// IntentContainsFold applies the ContainsFold predicate on the "intent" field.
func IntentContainsFold(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldContainsFold(FieldIntent, v))
}

// FlagsEQ applies the EQ predicate on the "flags" field.
func FlagsEQ(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldFlags, v))
}

// FlagsNEQ applies the NEQ predicate on the "flags" field.
func FlagsNEQ(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNEQ(FieldFlags, v))
}

// FlagsIn applies the In predicate on the "flags" field.
func FlagsIn(vs ...string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIn(FieldFlags, vs...))
}

// FlagsNotIn applies the NotIn predicate on the "flags" field.
func FlagsNotIn(vs ...string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotIn(FieldFlags, vs...))
}

// FlagsGT applies the GT predicate on the "flags" field.
func FlagsGT(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGT(FieldFlags, v))
}

// FlagsGTE applies the GTE predicate on the "flags" field.
func FlagsGTE(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGTE(FieldFlags, v))
}

// FlagsLT applies the LT predicate on the "flags" field.
func FlagsLT(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLT(FieldFlags, v))
}

// FlagsLTE applies the LTE predicate on the "flags" field.
func FlagsLTE(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLTE(FieldFlags, v))
}

// FlagsContains applies the Contains predicate on the "flags" field.
func FlagsContains(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldContains(FieldFlags, v))
}

// FlagsHasPrefix applies the HasPrefix predicate on the "flags" field.
func FlagsHasPrefix(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldHasPrefix(FieldFlags, v))
}

// FlagsHasSuffix applies the HasSuffix predicate on the "flags" field.
func FlagsHasSuffix(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldHasSuffix(FieldFlags, v))
}

// FlagsIsNil applies the IsNil predicate on the "flags" field.
func FlagsIsNil() predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIsNull(FieldFlags))
}

// FlagsNotNil applies the NotNil predicate on the "flags" field.
func FlagsNotNil() predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotNull(FieldFlags))
}

// FlagsEqualFold applies the EqualFold predicate on the "flags" field.
func FlagsEqualFold(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEqualFold(FieldFlags, v))
}

// FlagsContainsFold applies the ContainsFold predicate on the "flags" field.
func FlagsContainsFold(v string) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldContainsFold(FieldFlags, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InquiryKnowledge) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InquiryKnowledge) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InquiryKnowledge) predicate.InquiryKnowledge {
	return predicate.InquiryKnowledge(sql.NotPredicates(p))
}
